credentials:
  usernames:
    ribeiali:
      email: ribeiali@students.zhaw.ch
      name: ribeiali
      password: $2b$12$1o18pWIm.DWSWlSIjEzqsuciQ0d5fWtvbwo/JBkXutCB7cQhoMD32
    guest:
      name: guest
      password: $2b$12$bGavcuqm1Kq2VcZuCPm2Aekl9nEuLCn8TdmIGce/HManOyBt4u7KG
cookie:
  expiry_days: 30  # number of days until password is asked again
  key: wMrv1QThc783uEPX5OR701li7Xa46lLg # CodeIgniter Encryption Keysp
  name: streamlitcookie